version: '3.8'

services:
  front-devsecops:
    build:
      context: .
      dockerfile: Dockerfile
    image: derflinger/pep2devsecops_frontend
    container_name: pep2devsecops_frontend
    ports:
      - "3000:80"
    restart: always
