spring:
  application:
    name: LAB-TBD
  datasource:
    url: jdbc:postgresql://postgres-db:5432/LabTBD-2-2024
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8090

jwt:
  secret: OvmAbqM826GczKY1yF2MyYDjnAVcwKMPnL+OcobQ7bWDwf0IGy1YySsRTepJOI8j

# Configuración de Prometheus y Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name} 