version: "3.8"

services:
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: LabTBD-2-2024
    ports:
      - "5432:5432"

  app:
    container_name: pep2devsecops_backend
    image: niko085/pep2devsecops_backend
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/LabTBD-2-2024
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db

volumes:
  postgres_data:
