server:
  port: 8080

spring:
  application:
    name: pep1devsecops
  datasource:
    url: jdbc:postgresql://localhost:5432/dbdevsecops
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
