
spring:
  application:
    name: proyecto_docker
  jpa:
    show-sql: true
    hibernate:
      dialect: MySQL8Dialect
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbname: tingeso2023
    url: jdbc:mysql://localhost:3306/tingeso2023
    username: root
    password: password







server:
  port: 8080

spring:
  application:
    name: pep1devsecops
  datasource:
    url: jdbc:postgresql://localhost:5432/dbdevsecops
    username: postgres
    password: 12345678
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
