-- Insertar libros
INSERT INTO public.libros (titulo, autor, precio, stock, descripcion, anio)
VALUES ('El Quijote', 'Miguel de Cervantes', 20000, 10, 'Un clásico de la literatura española', 1605),
       ('Cien años de soledad', 'Gabriel García Márquez', 25000, 8, 'Novela emblemática del realismo mágico', 1967),
       ('1984', 'George Orwell', 18000, 12, 'Distopía sobre el control gubernamental', 1949),
       ('Fahrenheit 451', 'Ray Bradbury', 15000, 15, 'Crítica a la censura y el control de la información', 1953),
       ('Moby Dick', 'Herman Melville', 22000, 5, 'La obsesión del capitán Ahab por la ballena blanca', 1851),
       ('Orgullo y prejuicio', 'Jane Austen', 17000, 9, 'Romance y crítica social en la época victoriana', 1813),
       ('Los miserables', 'Victor Hugo', 28000, 7, 'Historia de redención y justicia social', 1862),
       ('El principito', 'Antoine de Saint-Exupéry', 12000, 20, 'Un cuento filosófico para todas las edades', 1943),
       ('La Odisea', 'Homero', 30000, 4, 'Las aventuras de Odiseo en su regreso a Ítaca', -700),
       ('Hamlet', 'William Shakespeare', 19000, 6, 'Tragedia sobre la venganza y la locura', 1603),
       ('Don Juan Tenorio', 'José Zorrilla', 16000, 10, 'La historia del legendario seductor', 1844),
       ('El retrato de Dorian Gray', 'Oscar Wilde', 21000, 12, 'Reflexión sobre la belleza y la corrupción', 1890),
       ('Crimen y castigo', 'Fiódor Dostoyevski', 27000, 8, 'Drama psicológico sobre la culpa y la redención', 1866),
       ('Drácula', 'Bram Stoker', 20000, 14, 'La historia del vampiro más famoso', 1897),
       ('Frankenstein', 'Mary Shelley', 19000, 11, 'Los peligros de jugar a ser Dios', 1818),
       ('Alicia en el país de las maravillas', 'Lewis Carroll', 15000, 16, 'Un viaje al surrealismo y la imaginación', 1865),
       ('Las aventuras de Sherlock Holmes', 'Arthur Conan Doyle', 18000, 9, 'Casos del detective más famoso', 1892),
       ('Los juegos del hambre', 'Suzanne Collins', 17000, 13, 'Distopía sobre la lucha por la supervivencia', 2008),
       ('El señor de los anillos', 'J.R.R. Tolkien', 35000, 5, 'La gran saga de la Tierra Media', 1954),
       ('Harry Potter y la piedra filosofal', 'J.K. Rowling', 22000, 18, 'El inicio de la aventura del joven mago', 1997),
       ('El código Da Vinci', 'Dan Brown', 23000, 10, 'Thriller sobre secretos religiosos y conspiraciones', 2003),
       ('La sombra del viento', 'Carlos Ruiz Zafón', 24000, 7, 'Misterio literario en la Barcelona de posguerra', 2001),
       ('El alquimista', 'Paulo Coelho', 16000, 12, 'Filosofía y búsqueda personal', 1988),
       ('It', 'Stephen King', 26000, 9, 'El terror de Pennywise en Derry', 1986),
       ('Los pilares de la tierra', 'Ken Follett', 29000, 6, 'La construcción de una catedral en la Edad Media', 1989),
       ('Dune', 'Frank Herbert', 32000, 4, 'Ciencia ficción y política en un universo desértico', 1965),
       ('Ready Player One', 'Ernest Cline', 18000, 15, 'Realidad virtual y cultura pop', 2011),
       ('Metro 2033', 'Dmitry Glukhovsky', 20000, 7, 'Supervivencia en los túneles del metro de Moscú', 2002),
       ('El nombre del viento', 'Patrick Rothfuss', 28000, 5, 'La historia del mago Kvothe', 2007),
       ('Cazadores de sombras', 'Cassandra Clare', 17000, 14, 'Mundos sobrenaturales y cazadores de demonios', 2007);
